server:
  context-path: /merchant
  port: 18080 # 18080, 18081
  shutdown: graceful

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    secure-port-enabled: false

spring:
  lifecycle:
    timeout-per-shutdown-phase: 60s # Server Shutdown wait time.
  application:
    name: wpay-core-merchant
  config:
    import:
      - optional:configserver:http://localhost:8888/resource
      - optional:configserver:http://localhost:8888/ecomerce
      - optional:configserver:http://localhost:8888/dbcon
  #######################
  # 404 HttpStatus Handling
  mvc:
    throw-exception-if-no-handler-found: true
    dispatch-options-request: false
  web:
    resources:
      add-mappings: false
  #######################
  # datasource: # Test H2 DB 접속 정보 설정
#    url: jdbc:h2:mem:wpay # H2 접속 정보
#    driver-class-name: org.h2.Driver # Database H2로 사용 하겠다.
#    username: wpay # H2 접속 시 입력할 username 정보 (원하는 것으로 입력)
#    password: wpay123! # H2 접속 시 입력할 password 정보 (원하는 것으로 입력)
  #######################
  jpa:
    hibernate:
      ddl-auto: create # h2 DB 연결 시만 사용.
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true # H2 Console 사용 여부 (H2 Database UI로 제공 기능)
      path: /h2-console # H2 Console Path [example: http://localhost/h2-console]

management: # 클라이언트 코드에서 Actuator 설정 (spring cloud config 사용을 위한 설정)
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  config: classpath:log4j2.yml # log4j2 설정 .yml 파일 경로 설정