server:
  context-path: /merchant
  port: 18081
  shutdown: graceful

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    secure-port-enabled: false

spring:
  lifecycle:
    timeout-per-shutdown-phase: 60s
  application:
    name: wpay-core-merchant

  #######################
  # 404 HttpStatus Handling
  #######################
  mvc:
    throw-exception-if-no-handler-found: true
    dispatch-options-request: false
  web:
    resources:
      add-mappings: false
  #######################
  # property 설정 파일 등록
  #######################
  config:
    import:
      - classpath:props/dev/external-mpi-dev.yml
  #######################
  # DB 접속 정보 설정
  #######################
  datasource:
    url: jdbc:h2:mem:wpay # H2 접속 정보
    driver-class-name: org.h2.Driver # Database H2로 사용 하겠다.
    username: wpay # H2 접속 시 입력할 username 정보 (원하는 것으로 입력)
    password: wpay123! # H2 접속 시 입력할 password 정보 (원하는 것으로 입력)
  #######################
  # JPA 설정
  #######################
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      data-locations: classpath:import.sql # 서버 실행 시 DML 수행
  h2:
    console:
      # H2 Console 사용 여부 (H2 Database UI로 제공 기능)
      enabled: true
      # H2 Console Path [example: http://localhost/h2-console]
      path: /h2-console

logging:
  # log4j2 설정 .yml 파일 경로 설정
  config: classpath:log4j2.yml